### ISSUE TITLE
Refreshing cache from outside

### ISSUE THREAD

**Issue by suraj3006** [pmylund/go-cache#19]
How can i refresh from outside process.

**Comment by pmylund** [comment]
I don't understand the question. Could you provide a little more detail?

**Comment by suraj3006** [comment]
Basically suppose I am running a http server and created instance of go
cache and added data from database. Now I wanted to refresh the cache
content once in every 30 minutes from database without restarting the
server. How can I do that.

**Comment by pmylund** [comment]
If you just want to expire items after 30 minutes, all you need to do is set the time to 30 minutes either when you create the cache (the defaultExpiration argument to New,) or when you add an item to the cache (the third argument to e.g. Set.) Then you can simply populate items when they don't exist in the cache, i.e. have expired, e.g.:

    // Setting up the cache
    c := cache.New(30*time.Minute, 45*time.Minute)

    // Later, in a function that uses the cache
    x, found := c.Get("foo")
    if found {
        // Use the cached value...
    } else {
        // Item expired/removed; need to refresh this item
        foo := expensiveDatabaseFunction("foo")
        c.Set("foo", foo, cache.DefaultExpiration)
    }

When you write programs like this, the functions that add data to the cache are the same ones that use the cache.

If you simply want to clear the entire cache from another goroutine, call c.Flush().
