### ISSUE TITLE
how to share cache between multiple different sessions of program.

### ISSUE THREAD

**Issue by saluru** [pmylund/go-cache#22]
Hi I'm trying to fetch an external json response and storing in to go-cache, but its not available for the  next time i call method, before its expiration time. Sharing the code snippet.

func GetRate() map[string]interface{} {
	c := cache.New(5*time.Minute, 4*time.Minute)
	getrate, found := c.Get("mortrate")
	if found {
		grate := getrate.(map[string]interface{})
		fmt.Printf("This is coming from cache \n")
		return grate

	} else { // func main() {
		fmt.Printf("We are going to fetch from mysite.com")
                resp, err := http.Get("mysite.com/getrate.htm?output=json")
                c.Set("resp", today, cache.DefaultExpiration)
               return resp
}

**Comment by pmylund** [comment]
Your key when setting the value is "resp", and "mortrate" when getting it. If you make the keys the same, it should work.

**Comment by saluru** [comment]
Sorry my bad, it was typo issue when i was opening issue, i maintained my key same for both. I'm loosing the key as i make second time GetRate call cache is getting fresh new cache reference.

**Comment by pmylund** [comment]
Can you post a complete example that exhibits the problem please?
